### ISSUE TITLE
[BUG] Different output directories on default/production and publish/build

### ISSUE THREAD

**Issue by cgnuechtel** [nx-dotnet/nx-dotnet#100] opened 2021-09-14 10:54 UTC
The output directories are different on _default_ configuration (debug)/_production_ configuration (release) and `@nx-dotnet/core:publish`/`@nx-dotnet/core:build` in `workspace.json`.

## Steps to reproduce the behavior 1:

1. Create a new Nx workspace
2. Generate a new .NET application with `npx nx generate @nx-dotnet/core:app my-app --template console --language C# --test-template none`
3. Run `npx nx build my-app` -> Build is stored in `<project-root>\dist\apps\my-app`
4. Open `workspace.json`
5. Add "output": "dist/apps/anything-else" to configurations -> productions like this: 
  ```
          "configurations": {
            "production": {
              "output": "dist/apps/anything-else",
              "configuration": "Release"
            }
          }
```
__If that configuration is used, the output is (incorrectly) stored under: `<project-root>/apps/my-app/dist/apps/anything-else`__
6. Change the `output` value under production to  `../../dist/apps/anything-else`
7. Run `npx nx build my-app --prod --skip-nx-cache` -> the output is stored under `<project-root>/dist/apps/anything-else`. In my opinion the change of step 6 is just a work-around and should not be necessary. Instead the behavior should be consistent to the default (debug) configuration.

## Steps to reproduce the behavior 2:

1. Undo step 6 of behavior 1
2. Change `builder` under `myapp` -> `architect` -> `build` from `@nx-dotnet/core:publish` to `@nx-dotnet/core:build`,
3. Run `npx nx build my-app --prod --skip-nx-cache` ->  the output is (correctly) stored under `<project-root>/dist/apps/anything-else`

## Expected behavior
The output path should be configured the same way on build/publish and debug/release

**Comment by AgentEnder** [comment] 2021-09-14 19:20
Hey @cgnuechte. Good catch! This is because we recently moved to executing the `dotnet` commands from project root instead of workspace root. I'll try to get a fix for this soon, but in the meantime you should be able to specify this path as a relative path as you mentioned.

**Comment by AgentEnder** [comment] 2021-09-14 19:21
If youre interested, this could be an easy PR, just in the publish / build executors you can use nodes path.relative method to calculate the path relative to the project source before passing it to the dotnet client.

**Comment by AgentEnder** [comment] 2021-09-14 19:22
Let me know if you are interested and I'll assign it to you, it will be about a week or so.

**Comment by cgnuechtel** [comment] 2021-09-15 08:06
Hi @AgentEnder Yes, that sounds great :-) I was always interested how to write a Nx plugin.

**Comment by AgentEnder** [comment] 2021-09-15 17:07
@cgnuechtel Actually, now that I'm looking at this I cannot reproduce it... Do you have a repro I can look at?

Are you on mac / linux or windows?

**Comment by AgentEnder** [comment] 2021-09-15 17:23
Never mind, I ended up figuring out what was going on. I had already updated this to use path.resolve beforehand, but did then was updating the wrong object so it was not getting passed correctly. This will be fixed in the next patch version, didn't mean to take control but it was just relocating a line 😄.

**Closed** 2021-09-15 17:49 UTC
Labels: bug, nx-dotnet/core, blocked-needs-repro

**Comment by cgnuechtel** [comment] 2021-09-16 13:36
@AgentEnder Fine! Even better :-) Thanks for solving this!

**Comment by AgentEnder** [comment] 2021-09-16 13:41
This was the relevant commit, if you wanted to see what change was needed: https://github.com/nx-dotnet/nx-dotnet/commit/30a7a265d508df1dd50818dbd02d94b4ed871c6d
