### ISSUE TITLE
[BUG] Generating webapi does not seem to work in new nx workspace

### ISSUE THREAD

**Issue by rudfoss** [nx-dotnet/nx-dotnet#838] opened 2024-03-07 13:53 UTC
### Current Behavior

Running the base generator for an application fails with error: `Cannot find configuration for '[app-name]-[app-name]'` (app name is repeated when parameter `--directory` is specified)

### Expected Behavior

Generator should generate webapi as expected.

### Steps to Reproduce

1. Create new nx-repo
```bash
pnpm create create-nx-workspace@latest dotnet-test --workspaceType=integrated --nxCloud=skip --preset=apps --defaultBase=main
```

2. Install `@nx-dotnet/core` and initialize
```bash
pnpm add -D @nx-dotnet/core
pnpm exec nx g @nx-dotnet/core:init
```

3. Run generator to create a webapi in c#
```bash
pnpm exec nx generate @nx-dotnet/core:application --name=admin-api --language=C# --directory=admin/api --template=webapi --testTemplate=xunit --pathScheme=nx --verbose=true
# or without --directory
pnpm exec nx generate @nx-dotnet/core:application --name=admin-api --language=C# --template=webapi --testTemplate=xunit --pathScheme=nx --verbose=true
```

Generator fails with ` Cannot find configuration for [app-name]`:

```
 NX  Generating @nx-dotnet/core:application

Executing Command: dotnet "new" "webapi" "--language" "C#" "--name" "DotnetTest.Admin.Api.AdminApi" "--output" "admin/api/admin-api"
The template "ASP.NET Core Web API" was created successfully.

Processing post-creation actions...
Restoring C:\projects\temp\dotnet-test\admin\api\admin-api\DotnetTest.Admin.Api.AdminApi.csproj:
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.


Executing Command: dotnet "new" "xunit" "--language" "C#" "--name" "DotnetTest.Admin.Api.AdminApi.Test" "--output" "admin/api/admin-api-test"
The template "xUnit Test Project" was created successfully.

Processing post-creation actions...
Restoring C:\projects\temp\dotnet-test\admin\api\admin-api-test\DotnetTest.Admin.Api.AdminApi.Test.csproj:
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.


Executing Command: dotnet "add" "admin/api/admin-api-test/DotnetTest.Admin.Api.AdminApi.Test.csproj" "reference" "admin/api/admin-api/DotnetTest.Admin.Api.AdminApi.csproj"
Reference `..\admin-api\DotnetTest.Admin.Api.AdminApi.csproj` added to the project.

 NX   Cannot find configuration for 'admin-api-admin-api'


Error: Cannot find configuration for 'admin-api-admin-api'
    at readProjectConfiguration (C:\projects\temp\dotnet-test\node_modules\.pnpm\nx@18.0.7\node_modules\nx\src\generators\utils\project-configuration.js:99:15)
    at C:\projects\temp\dotnet-test\node_modules\.pnpm\@nx-dotnet+core@2.2.0_@nx+js@18.0.7_nx@18.0.7\node_modules\@nx-dotnet\core\src\generators\add-swagger-target\add-swagger-target.js:11:63
    at Generator.next (<anonymous>)
    at C:\projects\temp\dotnet-test\node_modules\.pnpm\tslib@2.6.2\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\projects\temp\dotnet-test\node_modules\.pnpm\tslib@2.6.2\node_modules\tslib\tslib.js:165:16)
    at generateSwaggerSetup (C:\projects\temp\dotnet-test\node_modules\.pnpm\@nx-dotnet+core@2.2.0_@nx+js@18.0.7_nx@18.0.7\node_modules\@nx-dotnet\core\src\generators\add-swagger-target\add-swagger-target.js:9:20)
    at C:\projects\temp\dotnet-test\node_modules\.pnpm\@nx-dotnet+core@2.2.0_@nx+js@18.0.7_nx@18.0.7\node_modules\@nx-dotnet\core\src\generators\utils\generate-project.js:129:63
    at Generator.next (<anonymous>)
    at fulfilled (C:\projects\temp\dotnet-test\node_modules\.pnpm\tslib@2.6.2\node_modules\tslib\tslib.js:166:62)
```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.9.0
OS     : win32-x64
pnpm   : 8.15.4

nx             : 18.0.7
@nx/js         : 18.0.7
@nx/workspace  : 18.0.7
@nx/devkit     : 17.0.2
@nrwl/tao      : 18.0.7
typescript     : 5.4.2
---------------------------------------
Community plugins:
@nx-dotnet/core : 2.2.0
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@17.0.2
  - @nrwl/devkit@17.0.2

To fix this, run `nx migrate nx@18.0.7`
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default"
    ],
    "sharedGlobals": []
  },
  "plugins": [
    "@nx-dotnet/core"
  ]
}
```

### Additional Information

```bash
dotnet --version
8.0.102

pnpm -v
8.15.4

node -v
v20.9.0
```

**Comment by rudfoss** [comment] 2024-03-07 14:26
Current workaround.

1. Run the generator once until it fails.
2. Create `project.json` files for the app and test projects.
```
{
	"name": "admin-api",
	"$schema": "../../node_modules/nx/schemas/project-schema.json",
	"sourceRoot": "apps/admin-api",
	"projectType": "application",
	"targets": {},
	"tags": []
}
```

3. Delete all files and folders except the `project.json` files from each folder.
4. Re-run the generator. It succeeds since the project now exists in the nx graph.

**Comment by maxnatamo** [comment] 2024-03-22 10:52
I'm also having the same issue, but I can't replicate the solution from @rudfoss.

**Comment by mhdubose** [comment] 2024-03-28 00:40
This is a duplicate of https://github.com/nx-dotnet/nx-dotnet/issues/828

**Comment by AgentEnder** [comment] 2024-04-01 14:43
Hi, yea this should be fixed. I'll try to make some time this week to get something put together.

**Comment by rudfoss** [comment] 2024-04-01 15:12
Thanks for the updates and the quick fix guys! It is greatly appreciated.

**Comment by Den-dp** [comment] 2024-07-20 14:09
I'm getting `Cannot find configuration` when generating webapi, so it is still relevant.

```shell
> nx g @nx-dotnet/core:application --name=foo-webapi --language=C# --template=webapi --testTemplate=nunit --pathScheme=nx --verbose

 NX  Generating @nx-dotnet/core:application

Executing Command: dotnet "new" "webapi" "--language" "C#" "--name" "NxDotnet7Example.FooWebapi" "--output" "foo-webapi"
The template "ASP.NET Core Web API" was created successfully.

Processing post-creation actions...
Restoring C:\tmp\nx-dotnet7-example\foo-webapi\NxDotnet7Example.FooWebapi.csproj:
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.


Executing Command: dotnet "new" "nunit" "--language" "C#" "--name" "NxDotnet7Example.FooWebapi.Test" "--output" "foo-webapi-test"
The template "NUnit 3 Test Project" was created successfully.

Processing post-creation actions...
Restoring C:\tmp\nx-dotnet7-example\foo-webapi-test\NxDotnet7Example.FooWebapi.Test.csproj:
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.


Executing Command: dotnet "add" "foo-webapi-test/NxDotnet7Example.FooWebapi.Test.csproj" "reference" "foo-webapi/NxDotnet7Example.FooWebapi.csproj"
Reference `..\foo-webapi\NxDotnet7Example.FooWebapi.csproj` added to the project.

 NX   Cannot find configuration for 'foo-webapi'


Error: Cannot find configuration for 'foo-webapi'
    at readProjectConfiguration (C:\tmp\nx-dotnet7-example\node_modules\@nx-dotnet\core\node_modules\nx\src\generators\utils\project-configuration.js:101:15)
    at C:\tmp\nx-dotnet7-example\node_modules\@nx-dotnet\core\src\generators\add-swagger-target\add-swagger-target.js:11:63
    at Generator.next (<anonymous>)
    at C:\tmp\nx-dotnet7-example\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\tmp\nx-dotnet7-example\node_modules\tslib\tslib.js:165:16)
    at generateSwaggerSetup (C:\tmp\nx-dotnet7-example\node_modules\@nx-dotnet\core\src\generators\add-swagger-target\add-swagger-target.js:9:20)
    at C:\tmp\nx-dotnet7-example\node_modules\@nx-dotnet\core\src\generators\utils\generate-project.js:129:63
    at Generator.next (<anonymous>)
    at fulfilled (C:\tmp\nx-dotnet7-example\node_modules\tslib\tslib.js:166:62)
```

**Comment by AgentEnder** [comment] 2024-07-27 22:31
Hey, yeah - this has taken way too long but the fix is included in the Nx 19 PR

I'm going to merge it now and release, so update whenever you get a minute and we can verify.

**Closed** 2024-07-27 22:36 UTC
Labels: bug, scope: core

**Comment by Den-dp** [comment] 2024-07-29 12:05
@AgentEnder just checked with the latest `nx-dotnet` and `nx` and can confirm that it is fixed!

**Comment by Den-dp** [comment] 2024-07-29 12:08
This one is minor, but I found a blinking terminal on Windows while generating webapi types.

Haven't tried it yet but it looks like `windowsHide: true` here might fix the issue:
https://github.com/nx-dotnet/nx-dotnet/blob/629e6d89ed7df98d37c88f7b6d1ab871b3078cfb/packages/core/src/executors/openapi-codegen/executor.ts#L69-L78
