### ISSUE TITLE
[BUG] Not working with the nx daemon process enabled

### ISSUE THREAD

**Issue by pemsbr** [nx-dotnet/nx-dotnet#275] opened 2021-12-13 02:12 UTC
**Describe the bug**
Not working with the [Nx Daemon](https://nx.dev/l/a/guides/nx-daemon) process enabled.

**To Reproduce**

1. Enable the opt-in Nx Daemon process: 
```json
"tasksRunnerOptions": {
    "default": {
      "options": {
        "useDaemonProcess": true
      }
    }
  }
```

2. Open the Nx dependency graph.
```sh
nx dep-graph
```

3. `nx-dotnet` projects appear without any dependencies.

**Comment by AgentEnder** [comment] 2021-12-13 16:53
Hey, thanks for reporting this. Can you run `nx report` and include the output here?

Is there any additional logging when this happens?

**Comment by AgentEnder** [comment] 2021-12-14 04:33
I'm unable to reproduce this in 1.8.0 locally, do you care to check w/ latest?

**Comment by pemsbr** [comment] 2021-12-14 14:26
1.8.0 is still not working for me

```
Node : 16.5.0
  OS   : win32 x64
  npm  : 8.2.0

  nx : 13.3.2
  @nrwl/angular : undefined
  @nrwl/cli : 13.3.2
  @nrwl/cypress : 13.3.2
  @nrwl/devkit : 13.3.2
  @nrwl/eslint-plugin-nx : 13.3.2
  @nrwl/express : undefined
  @nrwl/jest : 13.3.2
  @nrwl/linter : 13.3.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.3.2
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.2
  @nrwl/web : 13.3.2
  @nrwl/workspace : 13.3.2
  @nrwl/storybook : 13.3.2
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.3.2
         @nx-dotnet/core: 1.8.0

(node:5228) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\code\web-ide\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by AgentEnder** [comment] 2021-12-20 15:41
Thats really weird, I can't reproduce this. Do you care to disable the daemon and grab a picture of your dep-graph?

**Comment by AgentEnder** [comment] 2022-01-16 21:32
@pemsbr Is this still occurring for you?

**Comment by pemsbr** [comment] 2022-01-18 11:32
I tried enabling it again and it's still happening. I'll do that, thanks 👍 

```console
Node : 17.3.1
  OS   : darwin arm64
  pnpm : 6.26.1
  
  nx : 13.4.5
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.4.5
  @nrwl/devkit : 13.4.5
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : undefined
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.5
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/web : 13.4.5
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.4.5
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 7.5.2
  ---------------------------------------
  Community plugins:
         @nrwl/js: 13.4.5
         @nx-dotnet/core: 1.8.0
```

**Comment by AgentEnder** [comment] 2022-02-08 03:00
I maintain that this issue should be fixed on Nx's side, but found the root cause while investigating the failing smoke tests. The `process.cwd()` is different when the daemon is active during `processProjectGraph()`,  leading to an ENOENT error when running `readFileSync('some-path/relative/to/workspace/root)`. The error messaging was hidden from logs due to us catching errors, so it wasn't visible.

**Closed** 2022-02-15 16:14 UTC
Labels: bug, scope: core, blocked-external, blocked-needs-repro
