### ISSUE TITLE
[BUG] Can't run command publish-local 'e2e-registry' task not found

### ISSUE THREAD

**Issue by asinino** [nx-dotnet/nx-dotnet#310] opened 2021-12-22 08:56 UTC
**Describe the bug**
Tried the suggested way to publish my changes locally so I can use them on my projects. Used "Cmder" terminal emulator so the "cp" command is available on Windows, but then it fails again with the message "ERROR: Task not found: "e2e-registry"".

**To Reproduce**

1. Run the command: `yarn publish-local`

**Expected behavior**
The command finish without errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/32019405/147065103-a76ff526-94ca-46a4-ba40-248ad08662da.png)

**Environment:**

- OS: Windows 10
- Version: 1.8.0
- Affected Packages: all

**Comment by AgentEnder** [comment] 2022-04-27 15:26
Duplicate of #309

**Closed by AgentEnder** 2022-04-27 15:26 UTC
Labels: bug, needs-triage
