### ISSUE TITLE
[BUG] --collect:"XPlat Code Coverage" doesn't include parameter quotes

### ISSUE THREAD

**Issue by barry-tormey-imprivata** [nx-dotnet/nx-dotnet#67] opened 2021-06-11 18:59 UTC
**Describe the bug**
When running `nx test --project my-project --collect:"XPlat Code Coverage"` the `collect` parameter is passed to `dotnet test` without the quotes resulting in an MS Build error:

> MSBUILD : error MSB1008: Only one project can be specified.
> Command failed: dotnet test MyProject.csproj --collect:XPlat Code Coverage

**To Reproduce**

1. Create a .NET app
2. Add [code coverage](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-code-coverage?tabs=linux)
3. Run `nx test --collect:"XPlat Code Coverage"`

**Expected behavior**
Expect parameters to be passed to `dotnet test` with the quotes such as
> dotnet test MyProject.csproj --collect:"XPlat Code Coverage"

**Environment:**

- OS: Windows 10
- Browser N/A
- Version 0.11.1
- Affected Packages @nx-dotnet/core

**Comment by bcallaghan-et** [comment] 2021-06-28 16:29
This behavior is caused by the shell scraping out the quotes before it reaches Nx or the test generator. The string received by the generator is `XPlat Code Coverage` without quotes. A workaround is to wrap the collect parameter with single-quotes so that the shell includes the double-quotes in the parameter's value. Your full test command would then be
```sh
nx test --project my-project --collect:'"XPlat Code Coverage"'
```

@AgentEnder We should consider quoting the values when building the `dotnet` command string. This could be done as needed, by checking if the string contains spaces, or simply quoting all user-provided values.

**Comment by AgentEnder** [comment] 2021-06-28 16:34
I think it would be best to only wrap if necessary. 

We should ensure that args fit these 2 criteria before adding quotes.
- Require Quotes
- Are not already quoted

This could be added to packages/utils/src/lib/utility-functions/paramters.ts

**Comment by tzuge** [comment] 2022-08-02 19:05
@AgentEnder should this specific case be handled with a `--codeCoverage` parameter on the test executor? (consistent with the nrwl jest executor). It could also run report generator create the html report.

**Comment by AgentEnder** [comment] 2022-08-02 20:20
I'm not sure that this issue is still valid since we swapped to using spawn for most things... This would be a good one to double check

**Comment by AgentEnder** [comment] 2022-11-03 14:30
I'm pretty sure this was fixed when we swapped to using spawn + param array over exec, I'm going to close it out.

**Closed by AgentEnder** 2022-11-03 14:30 UTC
Labels: bug, good first issue, scope: core
