### ISSUE TITLE
[BUG] CI NX Cached referenced dotnet projects will result in a failed build project of non-cached project

### ISSUE THREAD

**Issue by EelcoLos** [nx-dotnet/nx-dotnet#489] opened 2022-08-08 10:17 UTC
**Describe the bug**
When trying to build a project which uses another project, cached by NX, will result in a build failure for not finding the dll.

**To Reproduce**

1. Create a project (ie: 'ReferenceProject') with a class which will be called in the project B
2. run a CI build with ReferenceProject, making it cached
3. Create a second project (ie: 'CallingProject'), reference it to 'ReferenceProject'
4. Run this on the CI
5. the CI build will fail: 
> CSC : error CS0006: Metadata file '/home/vsts/work/1/s/obj/Debug/net6.0/ref/ReferenceProject.dll' could not be found [/home/vsts/work/1/s/CallingProject/CallingProject.csproj]

**Expected behavior**
Cached Projects will have their cached dll's referenced properly to dependant projects.

**Screenshots**
![image](https://user-images.githubusercontent.com/5102501/183389935-2a1cdaa8-d9e5-4550-894e-e87cfdf88c3f.png)

**Environment:**

- Pipeline builder: Azure Devops Pipelines
- NX Version: 14.5.2
- NX Dotnet version: 1.12.0

Edit: Workaround for this is to use a commit which will make the ReferenceProject rebuild. While this workaround works, it's also pretty tedious and defeats the purpose of using NX

**Comment by AgentEnder** [comment] 2022-08-08 14:53
@EelcoLos looking at the paths in the error message, it appears that your project doesn't send build outputs to `{workspaceRoot}/dist/...`.

Is this correct? Can you paste the `project.json` and `.csproj` files from the cached project here?

**Comment by EelcoLos** [comment] 2022-08-08 15:02
> Can you paste the project.json and .csproj files from the cached project here?

### nx.json
```json
{
	"npmScope": "meteninbim",
	"affected": {
		"defaultBase": "master"
	},
	"implicitDependencies": {
		"package.json": {
			"dependencies": "*",
			"devDependencies": "*"
		},
		".eslintrc.json": "*"
	},
	"tasksRunnerOptions": {
		"default": {
			"runner": "@nrwl/nx-cloud",
			"options": {
				"cacheableOperations": ["build", "lint", "test", "e2e"],
				"parallel": 3,
				"accessToken": ""
			}
		}
	},
	"plugins": ["@nx-dotnet/core"],
	"generators": {
		"@nrwl/angular:application": {
			"style": "scss",
			"linter": "eslint",
			"unitTestRunner": "jest",
			"e2eTestRunner": "cypress"
		},
		"@nrwl/angular:library": {
			"linter": "eslint",
			"unitTestRunner": "jest"
		},
		"@schematics/angular:component": {
			"style": "scss",
			"changeDetection": "OnPush",
			"project": "client",
			"path": "apps/client/src/app"
		},
		"@nrwl/angular:component": {
			"style": "scss"
		}
	},
	"$schema": "./node_modules/nx/schemas/nx-schema.json",
	"targetDefaults": {
		"build": {
			"dependsOn": ["^build"]
		}
	}
}
```

### workspace.json (extract only 'ReferenceProject')
```json
"business": {
			"$schema": "..\\..\\node_modules\\nx\\schemas\\project-schema.json",
			"root": "libs/business",
			"projectType": "library",
			"sourceRoot": "libs/business",
			"targets": {
				"build": {
					"executor": "@nx-dotnet/core:build",
					"outputs": ["dist/libs/business"],
					"options": {
						"configuration": "Debug",
						"noDependencies": true
					},
					"configurations": {
						"production": {
							"configuration": "Release"
						}
					}
				},
				"lint": {
					"executor": "@nx-dotnet/core:format"
				},
				"lint-fix": {
					"executor": "@nx-dotnet/core:format",
					"options": {
						"fix": true
					}
				}
			},
			"tags": ["nx-dotnet"]
		}
```

### workspace.json (CallingProject: Forge.Data)
```json
"forge-data": {
			"$schema": "..\\..\\..\\node_modules\\nx\\schemas\\project-schema.json",
			"sourceRoot": "libs/Meteninbim.Forge.Data",
			"root": "libs/Meteninbim.Forge.Data",
			"targets": {
				"build": {
					"executor": "@nx-dotnet/core:build",
					"outputs": ["dist/libs/Meteninbim.Forge.Data"],
					"options": {
						"configuration": "Debug",
						"noDependencies": true
					},
					"configurations": {
						"production": {
							"configuration": "Release"
						}
					}
				},
				"lint": {
					"executor": "@nx-dotnet/core:format"
				},
				"lint-fix": {
					"executor": "@nx-dotnet/core:format",
					"options": {
						"fix": true
					}
				}
			},
			"projectType": "library"
		},
```

### csproj of cached project

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>../../dist/libs/business</OutputPath>
    <CodeAnalysisRuleSet>..\..\apps\.sonarlint\ibis.meteninbim.projecten.apicsharp.ruleset</CodeAnalysisRuleSet>
    <Configurations>Debug;Release;DebugGenerate</Configurations>
  </PropertyGroup>
  <!-- <Target Name="CheckNxModuleBoundaries" BeforeTargets="Build">
    <Exec Command="node ../../node_modules/@nx-dotnet/core/src/tasks/check-module-boundaries.js -p business" />
  </Target> -->
  <ItemGroup>
    <AdditionalFiles Include="..\..\apps\.sonarlint\ibis.meteninbim.projecten.api\CSharp\SonarLint.xml" Link="SonarLint.xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="10.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\bimsync\Meteninbim.Bimsync.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Projects\GetReferenceProjects\" />
  </ItemGroup>
</Project>
```

**Comment by EelcoLos** [comment] 2022-08-08 15:55
@AgentEnder I'll do that first thing tomorrow.

**Comment by EelcoLos** [comment] 2022-08-09 08:57
sadly this did not work, though I think it's useful nonetheless
I luckily got this same issue at my workstation now, not only on the CI. What I notice is the incorrect reference to the dist folder. Inside is the sdk folder (net6.0) subfolder, which is not referenced

**Comment by EelcoLos** [comment] 2022-08-09 09:01
I did get an error when triggering this locally, with verbose this returned:
> dotnet execution returned status code 1
> Error: dotnet execution returned status code 1
> at DotNetClient.logAndExecute (C:\Users\elos\source\repos\DigitaalMeten\3d\meteninbim\node_modules\@nx->  dotnet\dotnet\src\lib\core\dotnet.client.js:159:19)
    at DotNetClient.build (C:\Users\elos\source\repos\DigitaalMeten\3d\meteninbim\node_modules\@nx-dotnet\dotnet\src\lib\core\dotnet.client.js:49:21)

**Comment by EelcoLos** [comment] 2022-08-09 09:06
Maybe good to point out that one of the projects is a .net standard 2.0 project and all others are .net 6

**Comment by EelcoLos** [comment] 2022-08-23 07:10
After some research, we probably found the culprit: a setting which defaulted by importing projects earlier.
The culprit itself was `noDependencies` on the outlier projects.

so the business project 
```json
"business": {
			"$schema": "..\\..\\node_modules\\nx\\schemas\\project-schema.json",
			"root": "libs/business",
			"projectType": "library",
			"sourceRoot": "libs/business",
			"targets": {
				"build": {
					"executor": "@nx-dotnet/core:build",
					"outputs": ["dist/libs/business"],
					"options": {
						"configuration": "Debug",
						"noDependencies": true
					},
					"configurations": {
						"production": {
							"configuration": "Release"
						}
					}
				},
				"lint": {
					"executor": "@nx-dotnet/core:format"
				},
				"lint-fix": {
					"executor": "@nx-dotnet/core:format",
					"options": {
						"fix": true
					}
				}
			},
			"tags": ["nx-dotnet"]
		}
```
which was imported a while ago using the `nx generate @nx-dotnet/core:import-projects` it was imported with `noDependencies` if I remember correctly.

The calling project **does** require the reference of said project (in the aforementioned case the forge-data):
```json
"forge-data": {
			"$schema": "..\\..\\..\\node_modules\\nx\\schemas\\project-schema.json",
			"sourceRoot": "libs/Meteninbim.Forge.Data",
			"root": "libs/Meteninbim.Forge.Data",
			"targets": {
				"build": {
					"executor": "@nx-dotnet/core:build",
					"outputs": ["dist/libs/Meteninbim.Forge.Data"],
					"options": {
						"configuration": "Debug",
						"noDependencies": true
					},
					"configurations": {
						"production": {
							"configuration": "Release"
						}
					}
				},
				"lint": {
					"executor": "@nx-dotnet/core:format"
				},
				"lint-fix": {
					"executor": "@nx-dotnet/core:format",
					"options": {
						"fix": true
					}
				}
			},
			"projectType": "library"
		},
```
Therefore, if the project tried to get the dependency, with `noDependencies` enabled, it'll assume the dll of the dependant project _is_ available already. Because it's not, it'll fail.

### Solution
The solution was to remove all `noDependencies`. 

The tidy up of having ${SourceRoot}/obj as extra output is a nice-to-have for future usage perhaps.

**Comment by AgentEnder** [comment] 2022-08-23 14:18
The dll should already be present, does your nx.json have targetDefaults / dependsOn setup for build?

The reason we pass `noDependencies` is to let Nx orchestrate the build of dependencies so that we can pull things back from the cache rather than having to actually build things.

**Comment by sanddigital** [comment] 2022-08-31 06:30
I'm experiencing this very same issue as noted in this thread. The only thing I can see that gets the builds to work is to use `"noDependencies": false`.

**nx.json** has this
`
"targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ]
    }
  }
  `
  
 **This are my local tools/package versions...**
![image](https://user-images.githubusercontent.com/1873105/187608264-8ee8198d-ef53-4147-9748-7160d13d5d9f.png)

I suspected the issue is that the built artifacts (dlls) are added to the output and was expecting them to be cached, however when the _reference_ project goes to find the dll from the output it has been cleared and therefore the build fails. It's like something is removing the output/cache as the projects are built. Why that happens is unclear.

Not really sure where to go next, except for now to force dependent projects to always build and not be able to take advantage of the nx cache.

Any ideas where to look?

**Comment by sanddigital** [comment] 2022-08-31 07:18
As is usually the way with this, I persisted some more and got it working using `"noDependencies": true` 😃 

I believe the issue I was facing was to do with some dotnet projects that had multi-framework targets defined. I was also using a static `options{ : output: "/some/output/path"}` on the build target. On each build of the target framework the static destination output was cleared on each target build.

By not specifying an  `options{ : output: "" }` and setting the target outputs to cache the _default_ `options.output` the builds then were able to build properly using the nx cache and without re-building dependencies.

```json
"targets": {
  "build": {
    "executor": "@nx-dotnet/core:build",
    "outputs": [
      "{options.output}"
    ],
    "options": {
      "configuration": "Debug",
      "noDependencies": true
    }
  }
}
```

**Comment by AgentEnder** [comment] 2022-10-24 15:40
I'm going to close this one out now, since its been a while without new info but also since it appears folks have figured out a solution path. I'll try to spend some time on this at some point to verify on my side, but this looks good now.

**Closed by AgentEnder** 2022-10-24 15:40 UTC
Labels: bug, scope: core
