### ISSUE TITLE
project.json not generated

### ISSUE THREAD

**Issue by jefedeltodos** [nx-dotnet/nx-dotnet#828] opened 2024-02-08 05:11 UTC
### Current Behavior

When generating a `library` or `application`, the `project.json` is not created.,

### Expected Behavior

The project.json file should be generated.  Without it, I cannot customize targets or other configuration options, like removing serve from libraries.

### Steps to Reproduce

1. Execute ` npx nx g @nx-dotnet/core:library -d services/libs/Domain --solutionFile MyApp.sln --language C# --template classlib --tags domain`
2. Select the options `xunit` for test framework and `dotnet` for naming conventions.
```zshell

>  NX  Generating @nx-dotnet/core:library

✔ Which template should be used for creating the tests project · xunit
✔ Which path naming conventions should the project use? · dotnet
Executing Command: dotnet "new" "classlib" "--language" "C#" "--name" "MyApp.Services.Libs.Domain" "--output" "services/libs/Domain"
The template "Class Library" was created successfully.

Processing post-creation actions...
Restoring /home/jefedeltodos/code/ccc/MyApp/MyApp/services/libs/Domain/MyApp.Services.Libs.Domain.csproj:
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.


Executing Command: dotnet "sln" "MyApp.sln" "add" "/home/jefedeltodos/code/ccc/MyApp/MyApp/services/libs/Domain"
Project `services/libs/Domain/MyApp.Services.Libs.Domain.csproj` added to the solution.
Executing Command: dotnet "new" "xunit" "--language" "C#" "--name" "MyApp.Services.Libs.Domain.Test" "--output" "services/libs/Domain.Test"
The template "xUnit Test Project" was created successfully.

Processing post-creation actions...
Restoring /home/jefedeltodos/code/ccc/MyApp/MyApp/services/libs/Domain.Test/MyApp.Services.Libs.Domain.Test.csproj:
  Determining projects to restore...
  Restored /home/jefedeltodos/code/ccc/MyApp/MyApp/services/libs/Domain.Test/MyApp.Services.Libs.Domain.Test.csproj (in 331 ms).
Restore succeeded.

Executing Command: dotnet "sln" "MyApp.sln" "add" "/home/jefedeltodos/code/ccc/MyApp/MyApp/services/libs/Domain.Test"
Project `services/libs/Domain.Test/MyApp.Services.Libs.Domain.Test.csproj` added to the solution.
Executing Command: dotnet "add" "services/libs/Domain.Test/MyApp.Services.Libs.Domain.Test.csproj" "reference" "services/libs/Domain/MyApp.Services.Libs.Domain.csproj"
Reference `..\Domain\MyApp.Services.Libs.Domain.csproj` added to the project.
CREATE services/libs/Domain/.gitignore

NOTE: The "dryRun" flag means no changes were made.
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : linux-x64
   npm    : 10.2.4
   
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/angular        : 18.0.2
   @nx/cypress        : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/playwright     : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.2
   @nx/webpack        : 18.0.2
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core : 2.2.0
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "neverConnectToCloud": true,
  "targetDefaults": {
    "build": {
      "cache": true,
      "dependsOn": [
        "^build"
      ],
      "inputs": [
        "production",
        "^production"
      ]
    },
    "@nx/jest:jest": {
      "cache": true,
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/jest.preset.js"
      ],
      "options": {
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    },
    "e2e": {
      "cache": true,
      "inputs": [
        "default",
        "^production"
      ]
    },
    "@nx/eslint:lint": {
      "cache": true,
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintignore",
        "{workspaceRoot}/eslint.config.js"
      ]
    }
  },
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/test-setup.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/eslint.config.js"
    ],
    "sharedGlobals": []
  },
  "generators": {
    "@nx/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "playwright"
    },
    "@nx/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nx/angular:component": {
      "style": "scss"
    }
  },
  "plugins": [
    {
      "plugin": "@nx-dotnet/core"
    }
  ]
}
```

**Comment by jefedeltodos** [comment] 2024-02-08 05:25
I just noticed that I'm getting the `NOTE: the "dryRun" flag means no changes were made` message despite my original command not passing the `--dry-run` argument.

Maybe that's why the project.json isn't being outputted.

**Comment by ghorsey** [comment] 2024-02-09 02:59
I found the workaround: `--dry-run` is being applied by default.

Using the following command created libraries as expected:
```zsh
npx nx g @nx-dotnet/core:library -d services/libs/Domain --solutionFile MyApp.sln --language C# --template classlib  --tags domain --dry-run=false
```
It seems that the exclusion of `--dry-run` is defaulting to `--dry-run=true`  and explicitly setting `--dry-run=false` is needed to output the project.json files.

**Comment by grimurd** [comment] 2024-02-16 14:47
--dry-run=false didn't work for me. I downgraded @nx-dotnet/core to v2.1 and after that everything works correctly.

**Comment by AgentEnder** [comment] 2024-02-20 03:35
-d is shorthand for dry run iirc, so that would cause this

**Comment by jefedeltodos** [comment] 2024-02-20 04:02
> -d is shorthand for dry run iirc, so that would cause this

This can be it.  The problem is running `npx nx g @nx-dotnet/core:library --help` has `-d` as an alias for `--directory`: 

```zsh
>  NX   generate @nx-dotnet/core:library [name] [options,...]


From:  @nx-dotnet/core (v2.0.0)
Name:  library (aliases: lib)


  Generate a dotnet project under the library directory.


Options:
    --language          Which language should the project use?                                                  [string]
    --name              The name assigned to the library                                                        [string]
    --testTemplate      Which template should be used for creating the                       [string] [default: "nunit"]
                        tests project?
    --directory, -d     A directory where the project is placed                                                 [string]
    --pathScheme        Determines if the project should follow NX or       [string] [choices: "nx", "dotnet"] [default:
                        dotnet path naming conventions                                                             "nx"]
    --skipSwaggerLib    By default, if using webapi template, an                               [boolean] [default: true]
                        additional library is scaffolded for swagger
                        files. This skips that setup.
    --solutionFile      Determines if the project should be added to a                             [string] OR [boolean]
                        solution file.
    --tags, -t          Add tags to the project (used for linting)                                              [string]
    --template          The template to instantiate when the command is                                         [string]
                        invoked. Each template might have specific
                        options you can pass.
```
but running `npx nx g --help` also shows that `-d` is an alias for `--dryRun`:
```zsh
nx generate <generator> [_..]

Generate or update source code (e.g., nx generate @nx/js:lib mylib).

Positionals:
  generator  Name of the generator (e.g., @nx/js:library, library)                                   [string] [required]

Options:
      --help         Show help                                                                                 [boolean]
      --version      Show version number                                                                       [boolean]
  -d, --dryRun       Preview the changes without updating files                               [boolean] [default: false]
      --interactive  When false disables interactive input prompts for options                 [boolean] [default: true]
      --verbose      Prints additional information about the commands (e.g., stack traces)                     [boolean]
      --quiet        Hides logs from tree operations (e.g. `CREATE package.json`)                              [boolean]

Run "nx g collection:generator --help" to see information about the generator's schema.
```
Could there be a conflict happening here?

So maybe remove the `-d` alias in this plugin, or is there a way to specify that the argument should be passed to the plugin?

**Comment by mhdubose** [comment] 2024-03-28 00:39
It doesn't look to me like this has anything to do with the directory vs dryrun flag. It looks like the project json file isn't being generated if Nx Crystal is enabled (see this line: https://vscode.dev/github/nx-dotnet/nx-dotnet/blob/master/packages/core/src/generators/utils/generate-project.ts#L192) which makes sense given the changes introduced by project Crystal. The problem is `add-swagger-target.ts` then goes on to call the nx function `readProjectConfiguration` (https://vscode.dev/github/nx-dotnet/nx-dotnet/blob/master/packages/core/src/generators/add-swagger-target/add-swagger-target.ts#L29) which attempts to find the project.json file that was explicitly skipped.

**Comment by mhdubose** [comment] 2024-03-28 00:49
You can work around this (albeit losing out on a feature) by adding `skipSwaggerLib=true` to the command

**Comment by mhdubose** [comment] 2024-03-28 01:26
It looks like the dryRun note is a red herring. The project.json file isn't being generated because of Nx Project Crystal being enabled. The overlapping flags should be addressed, but it's not the reason the project.json isn't there. The generator is checking if nx version is 18 or greater, and then checking for the environment variables `NX_PCV3` and `NX_CRYSTAL`. If either of those are set to false, the project.json file will be generated, despite the dry run message being displayed

```
NX_CRYSTAL='false'
nx g @nx-dotnet/core:lib --language C# --template classlib --verbose -d lib/test2 test2
 NX  Generating @nx-dotnet/core:library

√ Which template should be used for creating the tests project · xunit
√ Which path naming conventions should the project use? · nx
Executing Command: dotnet "new" "classlib" "--language" "C#" "--name" "Test.Lib.Test2" "--output" "lib/test2"
The template "Class Library" was created successfully.

Processing post-creation actions...
Restoring E:\src\test\lib\test2\Test.Lib.Test2.csproj:
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.

Executing Command: dotnet "new" "xunit" "--language" "C#" "--name" "Test.Lib.Test2.Test" "--output" "lib/test2-test"
The template "xUnit Test Project" was created successfully.

Processing post-creation actions...
Restoring E:\src\test\lib\test2-test\Test.Lib.Test2.Test.csproj:
  Determining projects to restore...
  All projects are up-to-date for restore.
Restore succeeded.

Executing Command: dotnet "add" "lib/test2-test/Test.Lib.Test2.Test.csproj" "reference" "lib/test2/Test.Lib.Test2.csproj"
Reference `..\test2\Test.Lib.Test2.csproj` added to the project.
CREATE lib/test2/project.json
CREATE lib/test2-test/project.json
CREATE lib/test2/.gitignore

NOTE: The "dryRun" flag means no changes were made.

**Comment by mhdubose** [comment] 2024-03-28 16:23
@AgentEnder It looks like your last commit removed `project.json` generation if Nx Crystal is enabled. Shouldn't we still generate a `project.json` file but simply omit the `targets` block since that's inferred?

**Comment by AgentEnder** [comment] 2024-04-01 14:45
Hi, I'm going to close this out as this issue was due to the dry run flag. #842 should target fixing #838 instead. Thanks!

**Closed by AgentEnder** 2024-04-01 14:45 UTC
Labels: bug
